### ISSUE TITLE
Text to Speech with MMS

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#251] opened 2023-09-01 20:55 UTC
SF may be very interested in converting chapters of the bible to audio - and because [Meta's MMS](https://huggingface.co/docs/transformers/model_doc/mms) can do this conversion, it may be feasible and valuable for Serval to do this.  It could be batch jobs, should be a simple amount of code to do this.  We could:
* Per line, make an audio file
* Per file in a corpora, make a file with timestamps per line
* Add new endpoint to download files
* Add new engine called TextToSpeech

**Comment by ddaspit** [comment] 2024-06-07 21:22
This is a duplicate of #186.

**Closed by ddaspit** 2024-06-07 21:22 UTC
Labels: duplicate
