### ISSUE TITLE
Key terms/glosses - full language support

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#492] opened 2024-08-22 19:41 UTC
Add support for Chinese simplified and traditional glosses.  This is already implemented in Serval.

**Comment by Enkidu93** [comment] 2024-08-22 19:46
@johnml1135, Chinese has not yet been added to Serval since it will require a bit more processing. Once it's added, I'm adding to add Chinese as well as the others (if any) that have not yet been added to silnlp to silnlp. Or if you'd rather Matthew do it, that's fine too. The Chinese will just need a bit of extra logic to get working.

**Comment by johnml1135** [comment] 2024-08-23 14:56
That's fine.  Eli, if you think you can get it into SILNLP most efficiently, then just do it.

**Comment by ddaspit** [comment] 2024-08-26 16:15
We could use the key terms corpus in Machine to do it. I wrote the code a while ago, so I don't remember, but it might be a significant rewrite. If that is the case, then it might not be worth it.

**Comment by mshannon-sil** [comment] 2024-09-24 18:22
This seems to largely be a duplicate of issue #440, so we should remember to close that issue as well.

**Closed** 2024-09-27 17:54 UTC
Labels: enhancement

**Comment by mshannon-sil** [comment] 2024-09-27 19:11
Why is this not planned? Is this not needed for the key terms functionality in Serval and SILNLP to match?

**Comment by ddaspit** [comment] 2024-09-27 20:19
I closed this as a duplicate.
