### ISSUE TITLE
Extract_corpora failing with incorrect error message about XML formatting for Settings.xml

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#58] opened 2021-07-01 18:01 UTC
The extract_corpora script is failing when trying to parse a valid XML file (e.g., _Settings.xml).  The issue appears to be the use of the '`parser=parser_utf8`' parameter on the calls to etree.parse.  Removing this parameter allows the script to process the _Settings.xml_ file correctly.  The error happens in both the `extract_project `and the `extract_term_renderings` methods.

Stack traces for both error scenarios below:

```
(silnlp-sQvaqLfK-py3.7) C:\Users\mm9q\PycharmProjects\silnlp>python -m silnlp.common.extract_corpora nhx_2021_07_01
2021-07-01 13:45:19,248 - silnlp.common.extract_corpora - INFO - Extracting nhx_2021_07_01...
Traceback (most recent call last):
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\extract_corpora.py", line 70, in <module>
    main()
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\extract_corpora.py", line 57, in main
    extract_project(project, args.include, args.exclude, args.markers)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\paratext.py", line 42, in extract_project
    settings_tree = etree.parse(str(project_dir / "Settings.xml"), parser=parser_utf8)
  File "src\lxml\etree.pyx", line 3521, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src\lxml\parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src\lxml\parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "file:/C:/Gutenberg/Paratext/projects/nhx_2021_07_01/Settings.xml", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

```
(silnlp-sQvaqLfK-py3.7) C:\Users\mm9q\PycharmProjects\silnlp>python -m silnlp.common.extract_corpora nhx_2021_07_01 
2021-07-01 13:48:57,874 - silnlp.common.extract_corpora - INFO - Extracting nhx_2021_07_01...
2021-07-01 13:49:05,577 - silnlp.common.paratext - INFO - # of Segments: 31104
Traceback (most recent call last):
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\extract_corpora.py", line 70, in <module>
    main()
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\extract_corpora.py", line 58, in main
    extract_term_renderings(project)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\paratext.py", line 192, in extract_term_renderings
    settings_tree = etree.parse(str(project_dir / "Settings.xml"), parser=parser_utf8)
  File "src\lxml\etree.pyx", line 3521, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src\lxml\parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src\lxml\parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "file:/C:/Gutenberg/Paratext/projects/nhx_2021_07_01/Settings.xml", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

**Comment by mmartin9684-sil** [comment] 2021-07-01 18:11
The problem seems to be happening when working with the TermRenderings.xml file; the _extract_term_renderings_ method fails when parsing the file.  Removing the '`parser=parser_utf8`' parameter from the `etree.parse` call corrects the problem.

```
C:\Users\mm9q\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-sQvaqLfK-py3.7\Scripts\python.exe -m silnlp.common.extract_corpora nhxRT_2021_07_01
2021-07-01 14:07:04,150 - silnlp.common.extract_corpora - INFO - Extracting nhxRT_2021_07_01...
2021-07-01 14:07:05,925 - silnlp.common.paratext - INFO - # of Segments: 31104
Traceback (most recent call last):
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\extract_corpora.py", line 70, in <module>
    main()
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\extract_corpora.py", line 58, in main
    extract_term_renderings(project)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\common\paratext.py", line 183, in extract_term_renderings
    renderings_tree = etree.parse(str(renderings_path), parser=parser_utf8)
  File "src\lxml\etree.pyx", line 3521, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src\lxml\parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src\lxml\parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "file:/C:/Gutenberg/Paratext/projects/nhxRT_2021_07_01/TermRenderings.xml", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

```

**Comment by johnml1135** [comment] 2021-07-01 21:04
This is a duplicate of #52.  I like the resolution though.

**Closed by johnml1135** 2021-07-01 21:04 UTC
