### ISSUE TITLE
Improve extraction where an opening marker absorbs the following whitespace.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#420] opened 2024-06-18 10:41 UTC
In the ESV the SFM is particularly complex and some extracted files occasionally missing a space between words.

```
\v 9 \wj “Blessed are \wj*\x + \xo 5:9 \xt James 3:18 \x*\wj the peacemakers, for \wj*\x + \xo 5:9 \xt 1 John 3:1 \x*\wj they shall be called \wj*\x + \xo 5:9 \xt Rom. 8:14\x*\wj sons\wj*\f + \fr 5:9 \ft Greek \+tl huioi\+tl*; see Preface\f*\wj of God.\wj*
```
->
```
“Blessed are the peacemakers, for they shall be called sonsof God.
```

```
\v 16 \wj In the same way, let your light shine before others, so \wj*\x + \xo 5:16 \xt Philem. 6; 1 Pet. 2:12 \x*\wj that\wj*\f + \fr 5:16 \ft Or \fq house. \fv 16\fq Let your light so shine before others that\f*\wj they may see your good works and \wj*\x + \xo 5:16 \xt John 15:8; 2 Cor. 9:13; Phil. 1:11; [ch. 9:8]\x*\wj give glory to your Father who is in heaven.\wj*
```
->
```
In the same way, let your light shine before others, so thatthey may see your good works and give glory to your Father who is in heaven.
```

I tested a few variations and the problem seems to be that the \wj marker absorbs the following whitespace. The complexity of the SFM markup doesn't seem to be an issue.

**Comment by AmeWenJ** [comment] 2024-11-05 20:56
The issue is already fixed with the new parser.

**Closed by AmeWenJ** 2024-11-05 20:56 UTC
Labels: bug, pipeline 2: extract, usfm

**Comment by ddaspit** [comment] 2024-11-05 22:49
@AmeWenJ Thanks for checking this out.
