### ISSUE TITLE
SentencePiece not processing Arabic text properly

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#127] opened 2022-03-01 19:55 UTC
When preprocessing an experiment that involves a typical Arabic language file with ~30K verses, SentencePiece vocabulary building fails unless the vocab size is set exceptionally low (~250-500 words).  The unigram trainer does very few tokenization passes, and reports unusually high num_tokens/piece values (> 2000).

Sample stack trace below:

`2022-03-01 14:49:20.983659: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-03-01 14:49:20.983943: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-03-01 14:49:24,521 - silnlp.common.environment - INFO - Using workspace: S: as per environment variable SIL_NLP_DATA_PATH.
2022-03-01 14:49:25,350 - silnlp.common.utils - INFO - Git commit: 43e5aecd6f
2022-03-01 14:49:25,380 - silnlp.nmt.config - INFO - Building source vocabulary...
builder.cc(480) LOG(INFO) Loading mapping file: C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\nmt_nfkc.tsv
builder.cc(153) LOG(INFO) Loading CharsMap of size=224709
builder.cc(209) LOG(INFO) Generated normalizer blob. size=237539
sentencepiece_trainer.cc(77) LOG(INFO) Starts training with : 
trainer_spec {
  input: S:MT\scripture\arb-ONAV.txt
  input_format:
  model_prefix: S:MT\experiments\BT-Arabic\Baseline.arb-en.ONAV-NIV\src-sp
  model_type: UNIGRAM
  vocab_size: 2500
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 1000000
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  user_defined_symbols: <blank>
  required_chars:
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  Γüç
}
normalizer_spec {
  name: user_defined
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv: C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\nmt_nfkc.tsv
}
denormalizer_spec {}
trainer_interface.cc(329) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(178) LOG(INFO) Loading corpus: S:MT\scripture\arb-ONAV.txt
trainer_interface.cc(385) LOG(INFO) Loaded all 31098 sentences
trainer_interface.cc(400) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(400) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(400) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(400) LOG(INFO) Adding meta_piece: <blank>
trainer_interface.cc(405) LOG(INFO) Normalizing sentences...
trainer_interface.cc(466) LOG(INFO) all chars count=4243507
trainer_interface.cc(487) LOG(INFO) Alphabet size=67
trainer_interface.cc(488) LOG(INFO) Final character coverage=1
trainer_interface.cc(520) LOG(INFO) Done! preprocessed 31098 sentences.
unigram_model_trainer.cc(139) LOG(INFO) Making suffix array...
unigram_model_trainer.cc(143) LOG(INFO) Extracting frequent sub strings...
unigram_model_trainer.cc(194) LOG(INFO) Initialized 660 seed sentencepieces
trainer_interface.cc(526) LOG(INFO) Tokenizing input sentences with whitespace: 31098
trainer_interface.cc(537) LOG(INFO) Done! 112748
unigram_model_trainer.cc(489) LOG(INFO) Using 112748 sentences for EM training
unigram_model_trainer.cc(505) LOG(INFO) EM sub_iter=0 size=476 obj=28.559 num_tokens=1043059 num_tokens/piece=2191.3
unigram_model_trainer.cc(505) LOG(INFO) EM sub_iter=1 size=421 obj=26.8342 num_tokens=1048014 num_tokens/piece=2489.34
trainer_interface.cc(615) LOG(INFO) Saving model: S:MT\experiments\BT-Arabic\Baseline.arb-en.ONAV-NIV\src-sp.model
Traceback (most recent call last):
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mm9q\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\preprocess.py", line 25, in <module>
    main()
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\preprocess.py", line 21, in main
    config.preprocess(args.stats)
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\config.py", line 702, in preprocess
    self._build_vocabs()
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\config.py", line 1548, in _build_vocabs
    self._create_unshared_vocab(self.src_isos, src_vocab_file_paths, "source")
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\config.py", line 1632, in _create_unshared_vocab
    build_vocab(vocab_file_paths, vocab_size, vocab_type, vocab_seed, casing,
  File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\config.py", line 397, in build_vocab
    sp.SentencePieceTrainer.Train(
  File "C:\Users\mm9q\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-sQvaqLfK-py3.8\lib\site-packages\sentencepiece\__init__.py", line 444, in Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "C:\Users\mm9q\AppData\Local\pypoetry\Cache\virtualenvs\silnlp-sQvaqLfK-py3.8\lib\site-packages\sentencepiece\__init__.py", line 389, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
RuntimeError: Internal: C:\projects\sentencepiece\src\trainer_interface.cc(590) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())] Vocabulary size too high (2500). Please set it to a value <= 426.
`

**Comment by ddaspit** [comment] 2022-03-07 06:53
After some investigation, I have determined the cause of this issue. By default, SentencePiece splits adjacent characters into separate tokens if they are in different Unicode scripts. Most of the characters in the Arabic texts are assigned to the "Arabic" script. Unfortunately, there a small number of very commonly occurring Arabic diacritics that are assigned to a special script called "Inherited". "Inherited" means that the character should be assigned to the same script as the preceding base character. Unfortunately, SentencePiece does not do this and instead treats "Inherited" as a separate script. I submitted an [issue](https://github.com/google/sentencepiece/issues/731) to the SentencePiece repo for this bug. The workaround for this bug is to set the `--split_by_unicode_script` option to `false`.

**Closed** 2022-03-07 07:13 UTC
Labels: bug

**Comment by ddaspit** [comment] 2022-03-07 07:15
I added a new configuration option `vocab_split_by_unicode_script` that can be set to `false` as a workaround until SentencePiece fixes the bug. There are source and target variants of this option as well (`src_vocab_split_by_unicode_script` and `trg_vocab_split_by_unicode_script`).
